### ISSUE TITLE
4.11 support?

### ISSUE THREAD

**Issue by michaelwbell** [mitchemmc/UE4FirstPersonVRTemplate#12]
Hi All! I was wondering if it was possible to update the template to 4.11? I have read that there are changes to the VR camera in 4.11. I am attempting to do that now, so that the camera is placed off the floor, though I have very limited experience with UE at the time of writing. I am sure an expert will do a far better job than me.

**Comment by mitchemmc** [comment]
Sorry, I have stopped working on this template in order to pursue a video series [https://www.youtube.com/c/mitchsvrlab/](url)
