### ISSUE TITLE
Licensing unclear

### ISSUE THREAD

**Issue by Xericore** [mitchemmc/UE4FirstPersonVRTemplate#9]
Hello. First of all, thank you for sharing this project.

I couldn't find any information about the licensing. 
I'd like to implement your template in a non-commercial demo.

If so, where do I have to give credit to your work? 
In-game in the distributed demo?
In a credits.txt that is in the download?
On the website where the demo will be distributed?

It would be helpful to me if you could clarify these questions. Thanks.
I suggest the MIT license.

**Comment by mitchemmc** [comment]
There should be a licence file in the root of the project if not (or you can't see it) let me know and I'll look into it, the gist of it is MIT licence credit if you like, don't if you don't

**Comment by Xericore** [comment]
Sorry, I must have overlooked that file. Thanks for the clarification, I will give you credit in the demo.
